name: Publish docs
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate HTML
        run: ./gradlew dokkaGenerate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          ssh-key: ${{ secrets.DEPLOY_KEY }}
